# this is used for development
# docker stack deploy -c docker-stack.yml ${NAME}
version: "3.0"
services:
  fltngmmth_dev:
    image: bresnow/fltngmmth_dev:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${NAME?What's the name of the app?}-http.rule=Host(`${NAME?What's the name of the app?}.fltngmmth.com`)
        - traefik.http.routers.${NAME?What's the name of the app?}-http.entrypoints=http
        - traefik.http.routers.${NAME?What's the name of the app?}-http.middlewares=https-redirect
        - traefik.http.routers.${NAME?What's the name of the app?}-https.rule=Host(`${NAME?What's the name of the app?}.fltngmmth.com`)
        - traefik.http.routers.${NAME?What's the name of the app?}-https.entrypoints=https
        - traefik.http.routers.${NAME?What's the name of the app?}-https.tls=true
        - traefik.http.routers.${NAME?What's the name of the app?}-https.tls.certresolver=le
        - traefik.http.services.${NAME?What's the name of the app?}.loadbalancer.server.port=5173
    volumes:
      - luvcraft1:/usr/src/app
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
volumes:
  luvcraft1:
    driver: local-persist
    driver_opts:
      mountpoint: ${VOLUME?What's the volume?}