# this is used for development
# docker stack deploy -c docker-stack.yml ${NAME}
version: "3.0"
services:
  fltngmmth_dev:
    image: bresnow/fltngmmth_dev:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.${NAME?What's the name of the app?}-http.rule=Host(`fltngmmth.com`)
        - traefik.http.routers.${NAME?What's the name of the app?}-http.entrypoints=http
        - traefik.http.routers.${NAME?What's the name of the app?}-http.middlewares=https-redirect
        - traefik.http.routers.${NAME?What's the name of the app?}-https.rule=Host(`fltngmmth.com`)
        - traefik.http.routers.${NAME?What's the name of the app?}-https.entrypoints=https
        - traefik.http.routers.${NAME?What's the name of the app?}-https.tls=true
        - traefik.http.routers.${NAME?What's the name of the app?}-https.tls.certresolver=le
        - traefik.http.routers.${NAME?What's the name of the app?}-https.service=${NAME?What's the name of the app?}
        - traefik.http.services.${NAME?What's the name of the app?}.loadbalancer.server.port=5173

        - traefik.http.routers.${NAME?What's the name of the app?}relay-http.rule=Host(`relay.fltngmmth.com`)
        - traefik.http.routers.${NAME?What's the name of the app?}relay-http.entrypoints=http
        - traefik.http.routers.${NAME?What's the name of the app?}relay-http.middlewares=https-redirect
        - traefik.http.routers.${NAME?What's the name of the app?}relay-https.rule=Host(`relay.fltngmmth.com`)
        - traefik.http.routers.${NAME?What's the name of the app?}relay-https.entrypoints=https
        - traefik.http.routers.${NAME?What's the name of the app?}relay-https.tls=true
        - traefik.http.routers.${NAME?What's the name of the app?}relay-https.tls.certresolver=le
        - traefik.http.routers.${NAME?What's the name of the app?}relay-https.service=${NAME?What's the name of the app?}relay
        - traefik.http.services.${NAME?What's the name of the app?}relay.loadbalancer.server.port=3369
    volumes:
      - ${PWD}:/usr/src/app
    networks:
      - traefik-public
networks:
  traefik-public:
    external: true
# volumes:
#   luvcraft1:
#     driver: local-persist
#     driver_opts:
#       mountpoint: ${PWD}