# this is used for local development and testing
version: "3.0"
services:
  dev:
    image: bresnow/fltngmmth_dev:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: development


